### ISSUE TITLE
declaration file not found

### ISSUE THREAD

**Issue by mfulton26** [GoogleChromeLabs/sw-appcache-behavior#12]
I'm getting the following when trying to import `appcache-polyfill-window` in a TypeScript file:

```txt
Could not find a declaration file for module 'appcache-polyfill-window'. './node_modules/appcache-polyfill-window/build/index.umd.js' implicitly has an 'any' type.
```

Does `"types"` need to be defined in `package.json` or perhaps `./node_modules/appcache-polyfill-window/build/packages/appcache-polyfill-window/index.d.ts` should be moved to `./node_modules/appcache-polyfill-window/build/index.d.ts`

**Comment by mfulton26** [comment]
I also get a compilation warning when running my react app, not sure if this is related though:

```txt
unable to locate 'node_modules/appcache-polyfill-window/build/index.mjs'
```

**Comment by mfulton26** [comment]
> I also get a compilation warning when running my react app, not sure if this is related though:
> 
> ```
> unable to locate 'node_modules/appcache-polyfill-window/build/index.mjs'
> ```

oh, should `index.modern.js` be `index.mjs`?

**Comment by jeffposnick** [comment]
Sorry, with the `v0.2.1` release I upgraded [`microbundle`](https://github.com/developit/microbundle), and that seems to have produced some slightly different built files.

I'll look into the TypeScript locations, but I'm basically using whatever `microbundle` does by default when it comes to that.

The `v0.2.1` release drops the `.mjs` extension from the built files. If you're using `appcache-polyfill-window` as an ES module, either via a bundler that supports ES modules or via `<script type="module">` HTML without a bundler, then you should be able to request the `index.modern.js` version.

Are you using a bundler, and if so, which? (`webpack`? Rollup? etc.)

**Comment by mfulton26** [comment]
webpack+Typescript

**Comment by mfulton26** [comment]
oh, so maybe I can do `import { init } from 'appcache-polyfill-window/build/index.modern';` instead of simply `import { init } from 'appcache-polyfill-window';`

**Comment by mfulton26** [comment]
that worked but I don't think it was necessary, I forgot that I had used `CopyWebpackPlugin` to copy both the sw umd and the window mjs but as you mentioned the mjs got renamed, now that I'm pulling in appcache-polyfill-window in my actual TypeScript code I shouldn't need to copy over the mjs/moder.js at all

**Comment by jeffposnick** [comment]
Yeah, if you'r using `webpack` to bundle your code, then

```
import { init } from 'appcache-polyfill-window';
```

should be fine, instead of using `CopyWebpackPlugin`. (It's hard to put out one-size-fits-all guidance given that each developer might be using a different build setup.)

I'm taking a look into the TypeScript definitions now in a sample project.

**Comment by jeffposnick** [comment]
Okay, I think I [figured out](https://github.com/GoogleChromeLabs/sw-appcache-behavior/commit/db9643690dbea5b0ae423dc3b03a9b390b77fec3) how to get the TypeScript setup happy in this PR, with the changes pushed out to `npm` as release `v0.2.2`.

Visual Studio's TypeScript integration is picking it up now. Let me know if you're still seeing any issues.

![Screen Shot 2020-05-27 at 3 47 04 PM](https://user-images.githubusercontent.com/1749548/83065475-8b5a1600-a031-11ea-94d4-4fbfc0391dba.png)
