### ISSUE TITLE
callback for when new cache is ready

### ISSUE THREAD

**Issue by mfulton26** [GoogleChromeLabs/sw-appcache-behavior#13]
From what I can tell every time I call `init({ cachePopulatedCallback })` the `cachePopulatedCallback` is invoked even if the cache wasn't changed.

I'm not sure yet if this is an issue with initialization or if that callback was intended to always be called even if the same cache is in use.

**Comment by jeffposnick** [comment]
What URLs are passed to the `cachePopulatedCallback` function?

Do you see corresponding requests for those URLs in the Network panel in DevTools?

**Comment by mfulton26** [comment]
I figured this out, it was a bug in the app I'm using this in around calling `reload` constantly 😄 

from what I can tell this is working great; thank you

**Comment by jeffposnick** [comment]
Great to hear!
