### ISSUE TITLE
Is there a way to tell if the cache or network was used for a given response?

### ISSUE THREAD

**Issue by thebigh2014** [GoogleChromeLabs/sw-appcache-behavior#21]
My web app, when used live, is intended to auto-refresh after the cache is refreshed (due to a change in the AppCache manifest - indicating an update to the app's code).  I need a way to tell if a given URL (returned in the urls array) was loaded from the network or from the cache.  Thanks in advance for advice/assistance.

**Comment by jeffposnick** [comment]
How were you previously making this determination when using AppCache? Could you share an excerpt of your code?

**Comment by thebigh2014** [comment]
I was relying on the appCache's `updateready` event, which only fires when the cache has been updated.

```window.applicationCache.addEventListener('updateready', reloadFunction);```

**Comment by jeffposnick** [comment]
(I may still be missing something, so apologies if this doesn't answer your question.)

The `cachePopulatedCallback` that this library [exposes](https://github.com/GoogleChromeLabs/sw-appcache-behavior#window-client) is meant to provide a hook that you could listen for to be notified when there's an update. It sounds like you're already using that and know how to access the URLs that were updated, but are specifically interested in whether or not during *the current page load*, a given URL was loaded directly from the network, or whether it passed through the service worker.

If that's the case, then I think you could obtain that info by calling [`performance.getEntriesByName(url)`](https://developer.mozilla.org/en-US/docs/Web/API/Performance/getEntriesByName). If the `workerStart` property of any of the entries returned is `0`, then the response did not pass through the service worker. If it's not `0`, then the response was returned by the service worker.

**Comment by thebigh2014** [comment]
> The `cachePopulatedCallback` that this library [exposes](https://github.com/GoogleChromeLabs/sw-appcache-behavior#window-client) is meant to provide a hook that you could listen for to be notified when there's an update. It sounds like you're already using that and know how to access the URLs that were updated, but are specifically interested in whether or not during _the current page load_, a given URL was loaded directly from the network, or whether it passed through the service worker.

Correct.

> If that's the case, then I think you could obtain that info by calling [`performance.getEntriesByName(url)`](https://developer.mozilla.org/en-US/docs/Web/API/Performance/getEntriesByName). If the `workerStart` property of any of the entries returned is `0`, then the response did not pass through the service worker. If it's not `0`, then the response was returned by the service worker.

I will see what I can do with this.  Thanks so much!

**Comment by thebigh2014** [comment]
I have tried using `performance.getEntriesByName(url)` but only once (likely a fluke) did I ever get `workerStart` being `0`.  Your suggestion of using the performance entries didn't indicate to me where to place it, so I put it in the `cachePopulatedCallback` that I defined in my `index.html` inline script – if this is incorrect, please let me know.

**Comment by jeffposnick** [comment]
Sorry. I realize now that because you're using a service worker that always calls `respondWith()`, the response will always pass through the service worker (after the first visit, once it's had a chance to take control). So `workerStart` won't actually have meaningful data for you.

It might be _possible_ to infer something via the other fields in the [`PerformanceEntry`](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceEntry), like checking the amount of time it took for the response to be returned and using some threshold like "anything over X milliseconds came from the network," but I can't imagine that would be reliable in practice.

So I'm ultimately unsure how you could get that information from inside of the `cachePopulatedCallback`.

**Comment by thebigh2014** [comment]
Yeah, I have no idea of getting a reliable indicator so I'm just not going to worry about it.  The user can just do a manual refresh or I might add some other way of the app being able to tell it is out of date.  Thanks for your assistance.
