### ISSUE TITLE
How best to mimic appcache behaviour using this?

### ISSUE THREAD

**Issue by gwynjudd** [GoogleChromeLabs/sw-appcache-behavior#3]
I'd like to be able to mimic the behaviour as best possible of the following. Any ideas or suggestions about how would be appreciated

`applicationCache.update()`

https://webplatform.github.io/docs/apis/appcache/ApplicationCache/update/

To update the cache by starting the cache download process. In the context of these modules, it would be useful to have a way to get `appcache-polyfill-window` to reload the cache manifest.

`applicationCache.status`

https://webplatform.github.io/docs/apis/appcache/ApplicationCache/status/

To figure out the current status of the cache. For example, having invoked the `update` equivalent, to determine if an update was detected, being downloaded, available etc

`applicationCache.ondownloading`

https://webplatform.github.io/docs/apis/appcache/ApplicationCache/ondownloading/

An event that would fire if an update is being downloaded.

`applicationCache.onupdateready`

https://webplatform.github.io/docs/apis/appcache/ApplicationCache/onupdateready

An event that would fire if an update has been downloaded and is available to be used

`applicationCache.onprogress`

https://webplatform.github.io/docs/apis/appcache/ApplicationCache/onprogress

An event that would fire when resources are being downloaded as part of a cache update

There are other events in the applicationCache API that may also be useful.

If there is any way to do this already, or some advice could be provided about how to do this kind of thing please let me know.

**Comment by jeffposnick** [comment]
Apologies, but mimicking those AppCache events are outside the scope of what this polyfill can provide. The focus is on providing the same caching/offline behavior.

You can accomplish some of what you describe by listening to corresponding [service worker lifecycle events](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle).
